const { test } = require('node:test')
const assert = require('node:assert/strict')

const {
  DEFAULT_EMAIL_TEMPLATE,
  EMAIL_TEMPLATE_OPTIONS,
  emailTemplateLabel,
  normalizeEmailTemplate
} = require('../rendering/email-template-options')
const { renderEmailReport } = require('../rendering/email-renderer')

const createSnapshot = () => ({
  schemaVersion: 1,
  location: {
    name: 'Shanghai <Central>',
    query: 'Shanghai'
  },
  source: {
    host: 'wttr.in',
    url: 'https://wttr.in/Shanghai?format=j1'
  },
  fetchedAt: '2026-06-17T08:00:00.000Z',
  current: {
    condition: 'Partly cloudy',
    description: 'Partly cloudy',
    temperatureC: 29,
    feelsLikeC: 33,
    humidityPercent: 76,
    windSpeedKph: 16,
    uvIndex: 7
  },
  daily: {
    date: '2026-06-17',
    minimumTemperatureC: 24,
    maximumTemperatureC: 33,
    uvIndex: 7
  },
  hourly: []
})

const createAdvice = () => ({
  schemaVersion: 1,
  subject: '[紫外线很强，注意防晒] 天气早报',
  focus: '午间紫外线较强',
  umbrella: '今天通常不用带伞',
  sunscreen: 'UV 7，建议认真防晒并尽量走阴凉处',
  clothing: '短袖或薄衬衫搭配轻薄下装',
  closing: '午间阳光强，出门记得做好防晒。',
  periods: [
    { label: '早通勤', summary: '多云，降雨概率最高 10% ，体感约 27°C' },
    { label: '午间', summary: '晴，降雨概率最高 0% ，体感约 33°C' }
  ],
  signals: {
    highestRiskLevel: 0,
    umbrellaLevel: 0,
    sunscreenLevel: 2,
    clothingLevel: 3,
    targetPrecipitationLevel: 0,
    thunderstorm: false,
    strongWind: false,
    dangerousHeat: false
  }
})

test('email template options preserve legacy ids labels and default fallback', () => {
  assert.equal(DEFAULT_EMAIL_TEMPLATE, '1')
  assert.deepEqual(EMAIL_TEMPLATE_OPTIONS, [
    ['1', '暖调风格'],
    ['2', '行动风格'],
    ['3', '玻璃渐变'],
    ['4', '极简风格'],
    ['5', '仪表风格']
  ])
  assert.equal(normalizeEmailTemplate('3'), '3')
  assert.equal(normalizeEmailTemplate('missing'), '1')
  assert.equal(emailTemplateLabel('5'), '仪表风格')
  assert.equal(emailTemplateLabel('missing'), '暖调风格')
})

test('all email templates render subject plain text html and action summary', () => {
  for (const [templateId, templateLabel] of EMAIL_TEMPLATE_OPTIONS) {
    const rendered = renderEmailReport({
      snapshot: createSnapshot(),
      advice: createAdvice(),
      recipient: {
        name: 'Mango',
        email: 'mango@example.com',
        emailTemplate: templateId,
        language: 'zh-CN'
      },
      branding: {
        reportTitle: 'Weather Morning Report',
        accentColor: '#4266a8',
        footerText: 'Generated by Weather Morning Report',
        greetingVisible: true,
        dataSourceVisible: true
      },
      reportType: 'morning',
      cached: false
    })

    assert.equal(rendered.templateId, templateId)
    assert.equal(rendered.templateLabel, templateLabel)
    assert.match(rendered.subject, /天气早报/)
    assert.match(rendered.text, /带伞/)
    assert.match(rendered.html, new RegExp(`data-email-template="${templateId}"`))
    assert.match(rendered.html, /<!doctype html>/)
    assert.match(rendered.html, /关键时段/)
    assert.deepEqual(rendered.actionSummary, {
      umbrella: '今天通常不用带伞',
      sunscreen: 'UV 7，建议认真防晒并尽量走阴凉处',
      clothing: '短袖或薄衬衫搭配轻薄下装',
      riskLevel: 0
    })
  }
})

test('email renderer escapes recipient location and footer values', () => {
  const rendered = renderEmailReport({
    snapshot: createSnapshot(),
    advice: createAdvice(),
    recipient: {
      name: '<script>alert(1)</script>',
      email: 'mango@example.com',
      emailTemplate: '1',
      language: 'zh-CN'
    },
    branding: {
      reportTitle: 'Weather <Morning>',
      accentColor: '#4266a8',
      footerText: '<img src=x onerror=alert(1)>',
      greetingVisible: true,
      dataSourceVisible: true
    },
    reportType: 'morning'
  })

  assert.doesNotMatch(rendered.html, /<script>alert/)
  assert.doesNotMatch(rendered.html, /<img src/)
  assert.match(rendered.html, /&lt;script&gt;alert\(1\)&lt;\/script&gt;/)
  assert.match(rendered.html, /Shanghai &lt;Central&gt;/)
  assert.match(rendered.html, /&lt;img src=x onerror=alert\(1\)&gt;/)
})

test('email renderer uses English labels when recipient language is English', () => {
  const advice = createAdvice()
  advice.subject = '[Strong UV, use sun protection] Weather report'
  advice.focus = 'Midday UV will be strong'
  advice.umbrella = 'An umbrella is usually unnecessary today'
  advice.sunscreen = 'UV 7; use sunscreen and seek shade'
  advice.clothing = 'Wear short sleeves or a thin shirt with lightweight bottoms'
  advice.closing = 'Midday sunlight will be strong; remember sun protection.'
  advice.periods = [
    { label: 'Morning commute', summary: 'Cloudy; rain up to 10%; feels like about 27°C' },
    { label: 'Midday', summary: 'Sunny; rain up to 0%; feels like about 33°C' }
  ]

  const rendered = renderEmailReport({
    snapshot: createSnapshot(),
    advice,
    recipient: {
      name: 'Mango',
      email: 'mango@example.com',
      emailTemplate: '4',
      language: 'en'
    },
    branding: {
      reportTitle: 'Weather Morning Report',
      accentColor: '#4266a8',
      footerText: 'Generated by Weather Morning Report',
      greetingVisible: true,
      dataSourceVisible: true
    },
    reportType: 'morning'
  })

  assert.match(rendered.subject, /Weather report/)
  assert.match(rendered.text, /Umbrella:/)
  assert.match(rendered.html, /Key periods/)
  assert.match(rendered.html, /Current conditions/)
})
