const REPORT_TYPES = ['morning', 'midday', 'evening']
const SEND_POLICIES = ['always', 'changes_only']
const LANGUAGES = ['zh-CN', 'en']
const SMTP_SECURITY_MODES = ['starttls', 'ssl', 'plain']

const createDefaultConfiguration = () => ({
  newUserDefaults: {
    locationName: 'Changning District, Shanghai',
    locationQuery: 'Changning,Shanghai',
    timezone: 'Asia/Shanghai',
    language: 'zh-CN',
    localSendTime: '08:30',
    reportType: 'morning',
    sendPolicy: 'always',
    scheduleEnabled: true
  },
  recipients: [],
  schedules: [],
  smtp: {
    host: '',
    port: 587,
    username: '',
    security: 'starttls',
    senderEmail: '',
    passwordSaved: false
  },
  providers: [
    { id: 'wttr-in', name: 'wttr.in', priority: 10, enabled: true, health: 'unknown', lastError: '' },
    { id: 'wttr-is', name: 'wttr.is', priority: 20, enabled: true, health: 'unknown', lastError: '' }
  ],
  branding: {
    reportTitle: 'Weather Morning Report',
    accentColor: '#4266a8',
    footerText: 'Generated by Weather Morning Report',
    greetingVisible: true,
    dataSourceVisible: true
  },
  notifications: {
    adminEmail: '',
    webhookUrl: '',
    retentionDays: 30,
    alertCooldownMinutes: 60,
    webhookEnabled: false,
    secretKeyBackupConfirmed: false
  }
})

module.exports = { REPORT_TYPES, SEND_POLICIES, LANGUAGES, SMTP_SECURITY_MODES, createDefaultConfiguration }
